//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminUser
    {
        public string AdminUserID { get; set; }
        public string Status { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public string UserID { get; set; }
    }
}
