//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AMPEntities : DbContext
    {
        public AMPEntities()
            : base("name=AMPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ComponentDate> ComponentDates { get; set; }
        public virtual DbSet<ComponentMaster> ComponentMasters { get; set; }
        public virtual DbSet<ImplementingOrganisation> ImplementingOrganisations { get; set; }
        public virtual DbSet<InputSectorCode> InputSectorCodes { get; set; }
        public virtual DbSet<Marker> Markers { get; set; }
        public virtual DbSet<ConditionalityReview> ConditionalityReviews { get; set; }
        public virtual DbSet<DSOMarker> DSOMarkers { get; set; }
        public virtual DbSet<Evaluation> Evaluations { get; set; }
        public virtual DbSet<Markers1> Markers1 { get; set; }
        public virtual DbSet<Performance> Performances { get; set; }
        public virtual DbSet<ProjectDate> ProjectDates { get; set; }
        public virtual DbSet<ProjectInfo> ProjectInfoes { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<ReviewARScore> ReviewARScores { get; set; }
        public virtual DbSet<ReviewDeferral> ReviewDeferrals { get; set; }
        public virtual DbSet<ReviewExemption> ReviewExemptions { get; set; }
        public virtual DbSet<ReviewMaster> ReviewMasters { get; set; }
        public virtual DbSet<ReviewOutput> ReviewOutputs { get; set; }
        public virtual DbSet<ReviewPCRScore> ReviewPCRScores { get; set; }
        public virtual DbSet<ReviewScore> ReviewScores { get; set; }
        public virtual DbSet<ReviewStage> ReviewStages { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<TeamExternal> TeamExternals { get; set; }
        public virtual DbSet<AdminUser> AdminUsers { get; set; }
        public virtual DbSet<BenefitingCountry> BenefitingCountries { get; set; }
        public virtual DbSet<BudgetCentre> BudgetCentres { get; set; }
        public virtual DbSet<CodePerformance> CodePerformances { get; set; }
        public virtual DbSet<ErrorLog> ErrorLogs { get; set; }
        public virtual DbSet<EvaluationManagement> EvaluationManagements { get; set; }
        public virtual DbSet<EvaluationType> EvaluationTypes { get; set; }
        public virtual DbSet<ExemptionReason> ExemptionReasons { get; set; }
        public virtual DbSet<FundingMech> FundingMeches { get; set; }
        public virtual DbSet<FundingMechToSector> FundingMechToSectors { get; set; }
        public virtual DbSet<InputSector> InputSectors { get; set; }
        public virtual DbSet<Logging> Loggings { get; set; }
        public virtual DbSet<Portfolio> Portfolios { get; set; }
        public virtual DbSet<ProjectRole> ProjectRoles { get; set; }
        public virtual DbSet<Risk> Risks { get; set; }
        public virtual DbSet<Stage> Stages { get; set; }
        public virtual DbSet<UserLookUp> UserLookUps { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<WorkflowMaster> WorkflowMasters { get; set; }
        public virtual DbSet<WorkflowStage> WorkflowStages { get; set; }
        public virtual DbSet<WorkflowTask> WorkflowTasks { get; set; }
        public virtual DbSet<Deferral> Deferrals { get; set; }
        public virtual DbSet<DeferralReason> DeferralReasons { get; set; }
        public virtual DbSet<ProjectBudgetCentreOrgUnit> ProjectBudgetCentreOrgUnits { get; set; }
        public virtual DbSet<OverallRiskRating> OverallRiskRatings { get; set; }
        public virtual DbSet<FundingArrangement> FundingArrangements { get; set; }
        public virtual DbSet<ProjectPlannedEndDate> ProjectPlannedEndDates { get; set; }
        public virtual DbSet<vHoDBudCentLookup> vHoDBudCentLookups { get; set; }
        public virtual DbSet<ProjectMaster> ProjectMasters { get; set; }
        public virtual DbSet<PartnerMaster> PartnerMasters { get; set; }
        public virtual DbSet<PartnerOrganisation> PartnerOrganisations { get; set; }
        public virtual DbSet<RiskImpact> RiskImpacts { get; set; }
        public virtual DbSet<RiskLikelihood> RiskLikelihoods { get; set; }
        public virtual DbSet<RiskRegister> RiskRegisters { get; set; }
        public virtual DbSet<RiskCategory> RiskCategories { get; set; }
        public virtual DbSet<DeliveryChain> DeliveryChains { get; set; }
        public virtual DbSet<EvaluationDocument> EvaluationDocuments { get; set; }
        public virtual DbSet<ReviewDocument> ReviewDocuments { get; set; }
        public virtual DbSet<RiskDocument> RiskDocuments { get; set; }
        public virtual DbSet<WorkflowDocument> WorkflowDocuments { get; set; }
        public virtual DbSet<AuditedFinancialStatement> AuditedFinancialStatements { get; set; }
    }
}
