//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConditionalityReview
    {
        public string ProjectID { get; set; }
        public string DisbursementSuspended { get; set; }
        public string cause { get; set; }
        public Nullable<System.DateTime> date_suspended { get; set; }
        public string consequences { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string UserID { get; set; }
    
        public virtual ProjectMaster ProjectMaster { get; set; }
    }
}
