//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deferral
    {
        public string ProjectID { get; set; }
        public string DeferralTimescale { get; set; }
        public string DeferralReason { get; set; }
        public string DeferralJustification { get; set; }
        public Nullable<System.DateTime> AnnualReviewDate { get; set; }
        public Nullable<System.DateTime> PCRDueDate { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
    
        public virtual ProjectMaster ProjectMaster { get; set; }
        public virtual ProjectMaster ProjectMaster1 { get; set; }
    }
}
