//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoggingMI
    {
        public int LogID { get; set; }
        public string Department { get; set; }
        public string Username { get; set; }
        public string ViewName { get; set; }
        public Nullable<System.DateTime> lastupdated { get; set; }
        public string Year { get; set; }
        public string Week { get; set; }
        public string Month { get; set; }
        public string ProjectID { get; set; }
    }
}
