//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OverallRiskRating
    {
        public int OverallRiskRatingId { get; set; }
        public string ProjectID { get; set; }
        public string Comments { get; set; }
        public string RiskScore { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
    
        public virtual Risk Risk { get; set; }
    }
}
