//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Performance
    {
        public string ProjectID { get; set; }
        public string ARRequired { get; set; }
        public string ARExemptJustification { get; set; }
        public Nullable<System.DateTime> ARDueDate { get; set; }
        public Nullable<System.DateTime> ARPromptDate { get; set; }
        public string ARDefferal { get; set; }
        public string PCRRequired { get; set; }
        public string PCRExemptJustification { get; set; }
        public Nullable<System.DateTime> PCRDueDate { get; set; }
        public Nullable<System.DateTime> PCRPrompt { get; set; }
        public string PCRDefferal { get; set; }
        public string PCRDefferalJustification { get; set; }
        public string PCRAuthorised { get; set; }
        public string ARExcemptReason { get; set; }
        public string PCRExcemptReason { get; set; }
        public Nullable<int> DefferalTimeScale { get; set; }
        public string DeferralReason { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string UserID { get; set; }
    
        public virtual ProjectMaster ProjectMaster { get; set; }
    }
}
