//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectDate
    {
        public string ProjectID { get; set; }
        public Nullable<System.DateTime> Created_date { get; set; }
        public Nullable<System.DateTime> FinancialStartDate { get; set; }
        public Nullable<System.DateTime> FinancialEndDate { get; set; }
        public Nullable<System.DateTime> OperationalStartDate { get; set; }
        public Nullable<System.DateTime> OperationalEndDate { get; set; }
        public Nullable<System.DateTime> ActualStartDate { get; set; }
        public Nullable<System.DateTime> PromptCompletionDate { get; set; }
        public Nullable<System.DateTime> ESNApprovedDate { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> ActualEndDate { get; set; }
        public Nullable<System.DateTime> ArchiveDate { get; set; }
    
        public virtual ProjectMaster ProjectMaster { get; set; }
    }
}
