//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectMaster
    {
        public ProjectMaster()
        {
            this.ComponentMasters = new HashSet<ComponentMaster>();
            this.Evaluations = new HashSet<Evaluation>();
            this.Portfolios = new HashSet<Portfolio>();
            this.ProjectBudgetCentreOrgUnits = new HashSet<ProjectBudgetCentreOrgUnit>();
            this.Reports = new HashSet<Report>();
            this.ReviewARScores = new HashSet<ReviewARScore>();
            this.ReviewDeferrals = new HashSet<ReviewDeferral>();
            this.ReviewDeferrals1 = new HashSet<ReviewDeferral>();
            this.ReviewExemptions = new HashSet<ReviewExemption>();
            this.ReviewMasters = new HashSet<ReviewMaster>();
            this.ReviewOutputs = new HashSet<ReviewOutput>();
            this.ReviewPCRScores = new HashSet<ReviewPCRScore>();
            this.Teams = new HashSet<Team>();
            this.TeamExternals = new HashSet<TeamExternal>();
            this.WorkflowMasters = new HashSet<WorkflowMaster>();
            this.RiskRegisters = new HashSet<RiskRegister>();
            this.RiskDocuments = new HashSet<RiskDocument>();
            this.AuditedFinancialStatements = new HashSet<AuditedFinancialStatement>();
        }
    
        public string ProjectID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string BudgetCentreID { get; set; }
        public string Stage { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string UserID { get; set; }
    
        public virtual ICollection<ComponentMaster> ComponentMasters { get; set; }
        public virtual ConditionalityReview ConditionalityReview { get; set; }
        public virtual DSOMarker DSOMarker { get; set; }
        public virtual ICollection<Evaluation> Evaluations { get; set; }
        public virtual Markers1 Markers1 { get; set; }
        public virtual Performance Performance { get; set; }
        public virtual ProjectDate ProjectDate { get; set; }
        public virtual ProjectInfo ProjectInfo { get; set; }
        public virtual Deferral Deferral { get; set; }
        public virtual Deferral Deferral1 { get; set; }
        public virtual ICollection<Portfolio> Portfolios { get; set; }
        public virtual ICollection<ProjectBudgetCentreOrgUnit> ProjectBudgetCentreOrgUnits { get; set; }
        public virtual BudgetCentre BudgetCentre { get; set; }
        public virtual Stage Stage1 { get; set; }
        public virtual ICollection<Report> Reports { get; set; }
        public virtual ICollection<ReviewARScore> ReviewARScores { get; set; }
        public virtual ICollection<ReviewDeferral> ReviewDeferrals { get; set; }
        public virtual ICollection<ReviewDeferral> ReviewDeferrals1 { get; set; }
        public virtual ICollection<ReviewExemption> ReviewExemptions { get; set; }
        public virtual ICollection<ReviewMaster> ReviewMasters { get; set; }
        public virtual ICollection<ReviewOutput> ReviewOutputs { get; set; }
        public virtual ICollection<ReviewPCRScore> ReviewPCRScores { get; set; }
        public virtual ICollection<Team> Teams { get; set; }
        public virtual ICollection<TeamExternal> TeamExternals { get; set; }
        public virtual ICollection<WorkflowMaster> WorkflowMasters { get; set; }
        public virtual ICollection<RiskRegister> RiskRegisters { get; set; }
        public virtual ICollection<RiskDocument> RiskDocuments { get; set; }
        public virtual ICollection<AuditedFinancialStatement> AuditedFinancialStatements { get; set; }
    }
}
