//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectInfo
    {
        public string ProjectID { get; set; }
        public string OVIS { get; set; }
        public string TeamMarker { get; set; }
        public string RiskAtApproval { get; set; }
        public string SpecificConditions { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string UserID { get; set; }
    
        public virtual ProjectMaster ProjectMaster { get; set; }
    }
}
