//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class ProjectHashtable
{
    public Nullable<int> CheckSumValue { get; set; }
    public string project { get; set; }
    public string description { get; set; }
    public string Purpose { get; set; }
    public string department { get; set; }
    public string Stage { get; set; }
    public string Status { get; set; }
    public System.DateTime last_update { get; set; }
    public string User { get; set; }
}
