//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReviewOutput
    {
        public string ProjectID { get; set; }
        public int ReviewID { get; set; }
        public int OutputID { get; set; }
        public string OutputDescription { get; set; }
        public Nullable<int> Weight { get; set; }
        public string OutputScore { get; set; }
        public Nullable<double> ImpactScore { get; set; }
        public string Risk { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string UserID { get; set; }
    
        public virtual ReviewMaster ReviewMaster { get; set; }
        public virtual ReviewScore ReviewScore { get; set; }
        public virtual ProjectMaster ProjectMaster { get; set; }
    }
}
