//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReviewStage
    {
        public ReviewStage()
        {
            this.ReviewDeferrals = new HashSet<ReviewDeferral>();
            this.ReviewDeferrals1 = new HashSet<ReviewDeferral>();
            this.ReviewExemptions = new HashSet<ReviewExemption>();
            this.ReviewMasters = new HashSet<ReviewMaster>();
        }
    
        public string StageID { get; set; }
        public string StageDescription { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string UserID { get; set; }
    
        public virtual ICollection<ReviewDeferral> ReviewDeferrals { get; set; }
        public virtual ICollection<ReviewDeferral> ReviewDeferrals1 { get; set; }
        public virtual ICollection<ReviewExemption> ReviewExemptions { get; set; }
        public virtual ICollection<ReviewMaster> ReviewMasters { get; set; }
    }
}
