//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReviewPCRScore
    {
        public string ProjectID { get; set; }
        public int ReviewID { get; set; }
        public string FinalOutputScore { get; set; }
        public string OutcomeScore { get; set; }
        public string ProgressToImpact { get; set; }
        public string CompletedToTimescales { get; set; }
        public string CompletedToCost { get; set; }
        public string FailedJustification { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string UserID { get; set; }
    
        public virtual ReviewMaster ReviewMaster { get; set; }
        public virtual ProjectMaster ProjectMaster { get; set; }
    }
}
