//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiskRegister
    {
        public int RiskID { get; set; }
        public string ProjectID { get; set; }
        public string RiskDescription { get; set; }
        public string Owner { get; set; }
        public int RiskCategory { get; set; }
        public Nullable<int> RiskLikelihood { get; set; }
        public Nullable<int> RiskImpact { get; set; }
        public string GrossRisk { get; set; }
        public string MitigationStrategy { get; set; }
        public Nullable<int> ResidualLikelihood { get; set; }
        public Nullable<int> ResidualImpact { get; set; }
        public string ResidualRisk { get; set; }
        public string Comments { get; set; }
        public string ExternalOwner { get; set; }
        public string Status { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public string UserID { get; set; }
    
        public virtual ProjectMaster ProjectMaster { get; set; }
        public virtual Risk Risk { get; set; }
        public virtual Risk Risk1 { get; set; }
        public virtual RiskCategory RiskCategory1 { get; set; }
    }
}
