//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public int ID { get; set; }
        public string ProjectID { get; set; }
        public string TeamID { get; set; }
        public string RoleID { get; set; }
        public string Status { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public string UserID { get; set; }
    
        public virtual ProjectRole ProjectRole { get; set; }
        public virtual ProjectRole ProjectRole1 { get; set; }
        public virtual ProjectMaster ProjectMaster { get; set; }
    }
}
