//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vHoDBudCentLookup
    {
        public string DisplayName { get; set; }
        public string EmpNo { get; set; }
        public string Grade { get; set; }
        public int GradeRank { get; set; }
        public string BudetCentre { get; set; }
        public string BudgetCentreDescription { get; set; }
        public string DivisionCode { get; set; }
        public string ProjectID { get; set; }
    }
}
