//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkflowMaster
    {
        public int WorkFlowID { get; set; }
        public int WorkFlowStepID { get; set; }
        public int TaskID { get; set; }
        public int StageID { get; set; }
        public string ProjectID { get; set; }
        public string ActionBy { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
        public string Recipient { get; set; }
        public string ActionComments { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string UserID { get; set; }
    
        public virtual WorkflowStage WorkflowStage { get; set; }
        public virtual WorkflowTask WorkflowTask { get; set; }
        public virtual ProjectMaster ProjectMaster { get; set; }
    }
}
